# Generated by Django 3.1.4 on 2020-12-28 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Person",
        ),
    ]
