# Generated by Django 3.1.4 on 2020-12-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_appointments_doctors_drugs_patients_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='smalltestclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('numer', models.IntegerField()),
            ],
        ),
    ]
